### ISSUE TITLE
Hello, I encountered this problem when I turned it on. Please help me have a look.

### ISSUE THREAD

**Issue by shizhanhao** [Qengineering/Jetson-Nano-image#13]
I use Jetson nano 4G B01
![6c9861c5913cab5951ffb24b483e498](https://user-images.githubusercontent.com/40157651/150920714-82deab08-326b-491f-a328-1bc6b2016415.jpg)

**Comment by Qengineering** [comment]
As can be read from the screen dump, an important symlink has been broken.
It isn't much you can do, except re-flash your SD card with a sane image.

**Comment by shizhanhao** [comment]
Thank you for your reply, which means I can't use this image, can I? Is this image made based on B01?

**Comment by shizhanhao** [comment]
Thank you for your reply, which means I can't use this image, can I? Is this image made based on B01?

**Comment by Qengineering** [comment]
The image is based on the Jetson Nano B01. We have one at the office and used it for the image. Once everything was working on this Nano, we made an image of the 32 GB SD-card and placed it on the net.
It should work.

**Comment by shizhanhao** [comment]
I see. Thank you again for your reply. I wish you all the best.
