### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by GTP95** [Qengineering/Jetson-Nano-image#14]
The instructions in the README say that the password is jetson, but what's the username? I'm trying to use your image on a headless jetson nano and to SSH into it (hoping there's an SSH server running out of the box) I also need the username. I tried to connect via serial but it didn't work.

**Comment by Qengineering** [comment]
The username is also **jetson**.
SSH is running out of the box as you can see below.
![image](https://user-images.githubusercontent.com/44409029/152636332-e07e87ec-b66d-4e82-a6b6-d0bbcb84e5e5.png)

**Comment by GTP95** [comment]
Thank you
