### ISSUE TITLE
img file size is too big

### ISSUE THREAD

**Issue by namwone** [Qengineering/Jetson-Nano-image#2]
Hi, I downloaded 7zip file (about 14GB) and unzipped.

however the img file is not 21GB but 57.7GB (62,021,173,248 bytes), so I couldn't flash the image on my SD card (32GB).

Is the actual image size 57.7GB? Or is there something I missed?

**Comment by YoungJonathanP** [comment]
I just unziped the image on OS-X using p7zip installed via homebrew and my image is 62.02GB

**Comment by Qengineering** [comment]
Dear @YoungJonathanP, @namwone ,

I'm working on a smaller image.

**Comment by Qengineering** [comment]
Fix it. Now we stay well within the 32 GB. Please download the image file again.
