### ISSUE TITLE
Link to image file broken

### ISSUE THREAD

**Issue by adammil2000** [Qengineering/Jetson-Nano-image#20]
Hi all,

Thanks so much for providing an image file, but currently the Gdrive link is broken. Can you please update? This is so useful to have.

The broken link is this one: https://drive.google.com/file/d/1753wRCFUV7U6vJa3H5xC1cq5MIcGKwFm/view?usp=sharing

Thanks!

**Comment by Qengineering** [comment]
Sorry for the inconvenience. The link has been restored.
