### ISSUE TITLE
No tensorflow?

### ISSUE THREAD

**Issue by prgrobots** [Qengineering/Jetson-Nano-image#22]
Hello,  just flashed the image and I am unable to import tensorflow with python or python3?

**Comment by Qengineering** [comment]
Sorry to hear @prgrobots .
I've downloaded the image myself just now, flashed it on a fresh SD card.
Below a screen dump. As you can see, everything worked well. 

![Screenshot from 2022-11-19 10-32-14](https://user-images.githubusercontent.com/44409029/202844774-2be27d65-274d-40aa-ad1a-6439251bf836.png)

I can't tell you what went wrong in your situation.

**Comment by Qengineering** [comment]
Great to hear!
