### ISSUE TITLE
Mount initialization error

### ISSUE THREAD

**Issue by YoungJonathanP** [Qengineering/Jetson-Nano-image#3]
From some initial research, there may be a conflict unpacking .7z files on OS-X. I tried creating images in 3 different ways, with the native unzip as described on the [Nvidia imaging page](https://developer.nvidia.com/embedded/learn/get-started-jetson-nano-devkit#:~:text=You%20can%20either%20write%20the%20SD%20card%20image%20using%20a%20graphical%20program%20like%20Etcher%2C%20or%20via%20command%20line.), with the [Unarchiver](https://theunarchiver.com/), and with a [homebrew install](https://apple.stackexchange.com/questions/307377/how-can-i-unpack-7z-files-via-macos-terminal#:~:text=You%20can%20install%20p7zip%20with%20Homebrew.%20So) of 7zip. The JetsonNano.7z unpacks into a .img file (which is required for both Imager and Etcher, as neither support .7z), and after several attempts in various ways (using both imager, etcher, and [cmd line instructions](https://developer.nvidia.com/embedded/learn/get-started-jetson-nano-devkit#:~:text=Command%20Line%20Instructions) ) the same thing happens at every boot attempt, as follows:
```
[   1.177435] tegradc tegradc.1: dpd enable lookup fail:-19
[   1.385966] imx219 7-0010: imx219_board_setup: error during i2c read probe (-121)
[   1.386098] imx219 7-0010: board setup failed
[   1.410380] imx219 8-0010: imx219_board_setup: error during i2c read probe (-121)
[   1.410457] imx219 8-0010: board setup failed
mount: /mnt: wrong fs type, bad option, bad superblock on /dev/mcblk0p1, missing codepage or helper program, or other error.
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
bash-4.4#
```
**ls** shows standard directories and in the /dev/ folder shows mmcblk0 through mmcblk0p9

Is there a mounting procedure that can correct this from here?

**Comment by Qengineering** [comment]
Dear @YoungJonathanP,

Hopefully [this zip file](https://drive.google.com/file/d/1Vb1H-0TxLfedZTu6c1pIURRzbtzjmJ4i/view?usp=sharing) (10.7 GB) can be loaded directly in the imager (or etcher) to write the image directly on SD.

**Comment by YoungJonathanP** [comment]
@Qengineering Thanks for the expedient response. I will test it today and let you know how it works.

**Comment by YoungJonathanP** [comment]
Unfortunately it is the same issue. I have a response from the Nvidia Jetson Nano team [here](https://forums.developer.nvidia.com/t/mount-error/183596/3) but I am not as familiar with the differences of kernal and "mount file systems"

**Comment by Qengineering** [comment]
Dear @YoungJonathanP,

Do I understand correctly? Did you also try the native NVIDIA image initially? Because if this image doesn't work, you've got a problem. This should create an image that works flawlessly on the Jetson Nano. Always.
This has nothing to do with NVIDIA's answer. There is more talk about the ability to boot from another drive, such as a USB drive.
My advice, try downloading and writing the original image form the official page, with another system (like a simple Windows PC) and see if it works.

**Comment by YoungJonathanP** [comment]
Thanks for the reply @Qengineering,

Following the instructions from [Nvidia](https://developer.nvidia.com/embedded/learn/get-started-jetson-nano-devkit#write) I am able to create an image from their resources. I have not been able to build a bootable image from any other (non-Nvidia) source. If the process to make an SD card image is different than what Nvidia documents, or if an additional step is required, I am eager to know.
Thank you

**Comment by Qengineering** [comment]
Dear @YoungJonathanP,

I tried the zip file of the image on our GitHub page on a simple Windows 7 machine with Etcher by following the steps NVIDIA provides under the "Instructions for Windows" tab. It works flawlessly. The Jetson Nano boots up immediately.
I'm not sure what's causing your problem.
It is best to manually install OpenCV and/or TensorFlow-Pytorch. It will take some time, but considering the time it takes to fix the image problem so far, it seems like the best option for now.

Thanks for your patience.

**Comment by YoungJonathanP** [comment]
Greetings @Qengineering,
I recently obtained an SD card adapter for my PC, and either through the combination of creating the image via my PC or downloading the new image from Google Drive, I am happy to say it works! I will test again later with OS-X.

Thanks again!
