### ISSUE TITLE
Could you add a vesion with add Pre-installed NCNN, MNN like RPi-image repo ? 

### ISSUE THREAD

**Issue by tonhathuy** [Qengineering/Jetson-Nano-image#5]

**Comment by Qengineering** [comment]
Dear @tonhathuy 

We didn't put the ncnn and MNN framework on our image because it's really simple to install both packages.
See our guides [ncnn](https://qengineering.eu/install-ncnn-on-jetson-nano.html) and [MNN](https://qengineering.eu/install-mnn-on-jetson-nano.html) If you need any assistance, please don't hesitate to contact us.

**Comment by tonhathuy** [comment]
I had built MNN to follow your guides. Base on your jetson DNN image repo. But when I run cmake, OpenCL, OpenGL and Vulkan is OFF . Can I continue ?. Thank you!
![Screenshot from 2021-08-04 18-02-03](https://user-images.githubusercontent.com/45118883/128170630-5fe31ceb-b221-4384-a93e-a70b4cd226eb.png)

**Comment by Qengineering** [comment]
I've checked it also. Vulkan, OpenCL and OpenGL are not installed on the JetPack I've used to build the image.
However, MNN is still using CUDA. So, if it's not a problem for you, please continue. I'll look into the missing Vulkan, OpenCL and GL on a later moment

**Comment by tonhathuy** [comment]
I continue to build "make -j4" with no success. It seems to be an error in cuDNN 
![Screenshot from 2021-08-04 19-02-14](https://user-images.githubusercontent.com/45118883/128177346-f6834cae-f180-4b37-b817-2359f0d74c81.png)

**Comment by Qengineering** [comment]
I see there is a new JetPack version 4.6.
I'm going to make an SDimage with ncnn and MNN, besides OpenCV, TensorFlow and the others.
Let me see what's happening when I try to install MNN here at the office. To be continued.

**Comment by Qengineering** [comment]
There are a few issues with MNN at the moment.
To install it on a Jetson Nano, please update the current GitHub version of MNN with pull request #1530 and ##1616. Build without TensorRT for now. To be continued.

**Comment by tonhathuy** [comment]
Thank you so much; I'm looking forward to it.

**Comment by Qengineering** [comment]
Dear @tonhathuy 
I've updated the image. Besides the latest versions of the original software you will now find also ncnn, MNN on board.
