### ISSUE TITLE
Request for ANPR on Jetson Nano

### ISSUE THREAD

**Issue by rsingh2083** [Qengineering/Jetson-Nano-image#6]
Hi Sir,

Any possibility of you working and releasing ANPR on jetson nano ?

**Comment by Qengineering** [comment]
Dear @rsingh2083,

Not in the nearby future. It's a rather complex problem. With a simple OCR, you get every text, including advertisement on the side of a truck. Detecting the location of the number plate, or places is also not so easy. A lot of programming. For now, I would search GitHub or the net for a solution.

**Comment by rsingh2083** [comment]
Ok Sir
