### ISSUE TITLE
OpenCV version under Python3 is 4.1.1, not 4.5.3

### ISSUE THREAD

**Issue by Andreslion** [Qengineering/Jetson-Nano-image#7]
Hi. Just installed this image and checked the version of OpenCV under Python3.   
It shows 4.1.1, not 4.5.3.
Python (2.7) shows OpenCV 4.5.3 though.
How can I use CV2 4.5.3 with Python3?
Thanks
![Python3 CV2 411](https://user-images.githubusercontent.com/42724570/133554140-fe83fb66-f6fb-49ca-8694-fe55ad2470de.png)

**Comment by Qengineering** [comment]
Did you not install any other software later?
Not OpenCV, but other software like GStreamer or PaddlePaddle install an OpenCV version. Usually not the most recent.
However, we will check the Gdrive link and verify the OpenCV version if necessary.

**Comment by Andreslion** [comment]
Nope, I didn't install anything after first boot. Not even connected to the internet. 
Just changed the username (jetson) and the host name (nano). Then checked the OpenCV versions for python and python3.

**Comment by Qengineering** [comment]
OK, we will download the file from GDrive and check the version. Will be back to you asap.

**Comment by Qengineering** [comment]
You were absolutely right! 
We have uploaded a new image (now with OpenCV 4.5.3) and refreshed the GDrive link.
Please download and flash again. Sorry for the inconvenience.
